//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unity.VisualScripting.Generated.PropertyProviders
{
	
	
	[global::Unity.VisualScripting.SerializedPropertyProviderAttribute(typeof(global::DigitalOpus.MB.Core.ShaderTextureProperty))]
	public class PropertyProvider_DigitalOpus_MB_Core_ShaderTextureProperty : Unity.VisualScripting.SerializedPropertyProvider<DigitalOpus.MB.Core.ShaderTextureProperty>
	{
	}
}
